name: iOS develop workflow

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  unit-tests:
    name: Slather
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Pull LFS objects
        run: git lfs pull

      - name: Install Slather
        run: gem install slather

      #- name: Install pods
      #  run: pod install

      - name: Run Unit Tests
        run: xcodebuild -project BitriseUnitTestSample.xcodeproj -scheme BitriseUnitTestSample -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" clean test | xcpretty

      - name: Generate report
        if: ${{ failure() }}
        run: slather coverage --html --scheme BitriseUnitTestSample BitriseUnitTestSample.xcodeproj

      - name: Upload Slather report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Slather Report
          path: ./html/*

      - name: Create file test_success.txt and write 'true' into it
        if: ${{ success() }}
        run: echo 'true' > test_success.txt

      - name: Create file test_success.txt and write 'false' into it
        if: ${{ failure() }}
        run: echo 'false' > test_success.txt

      - name: Upload file test_success.txt
        uses: actions/upload-artifact@v2
        with:
          name: pass_file
          path: test_success.txt

  dependency-check:
    needs: [unit-tests]
    if: always()
    name: Dependency Check
    runs-on: macos-latest

    steps:
      - name: Download file test_success.txt
        uses: actions/download-artifact@v2
        with:
          name: pass_file
          path: test_success.txt

      - name: Read file test_success.txt and set output parameter
        id: set_output
        run: echo "::set-output name=test_success::$(<pass_file/test_success.txt)"

      - name: Checkout the repository
        if: steps.set_output.outputs.test_success == 'true'
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Pull LFS objects
        run: git lfs pull

      - name: Install dependency-check
        run: brew update && brew install dependency-check

      - name: dependency-check run
        run: dependency-check --out . --scan .

      - name: Upload dependency-check report
        uses: actions/upload-artifact@v2
        with:
          name: Dependency Check Report
          path: dependency-check-report.html
          
  kiuwan:
    needs: [unit-tests]
    if: always()
    name: Kiuwan
    runs-on: ubuntu-latest
    
    steps:

      - name: Download file test_success.txt
        uses: actions/download-artifact@v2
        with:
          name: pass_file
          path: test_success.txt

      - name: Read file test_success.txt and set output parameter
        id: set_output
        run: echo "::set-output name=test_success::$(<pass_file/test_success.txt)"

      - name: Checkout the repository
        if: steps.set_output.outputs.test_success == 'false'
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Pull LFS objects
        run: git lfs pull

      - name: Checkout KiuwanLocalAnalyzer
        uses: actions/checkout@v2
        with:
          repository: aitoromg/kiuwan_mobility
          token: ${{ secrets.PAT }}
          path: ./

      - name: Run KiuwanLocalAnalyzer
        uses: ./
        with:
          softwareName: gsc:sgt:sd-purchase-experience:ios-ci
          sourcePath: ./
          user: ${{ secrets.KIUWAN_USER }}
          pass: ${{ secrets.KIUWAN_PASS }}
        continue-on-error: true

      - uses: actions/upload-artifact@v2
        with:
          name: Kiuwan Report
          path: ./kiuwan_report.pdf
          
  build_app:
    needs: [unit-tests]
    if: always()
    name: Build APP & Deploy to AppCenter
    runs-on: macos-latest
    
    steps:

      - name: Download file test_success.txt
        uses: actions/download-artifact@v2
        with:
          name: pass_file
          path: test_success.txt

      - name: Read file test_success.txt and set output parameter
        id: set_output
        run: echo "::set-output name=test_success::$(<pass_file/test_success.txt)"

      - name: Checkout the repository
        if: steps.set_output.outputs.test_success == 'true'
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Pull LFS objects
        run: git lfs pull
        
      - name: Build APP
        run: xcodebuild build-for-testing -project BitriseUnitTestSample.xcodeproj -scheme BitriseUnitTestSample -destination "platform=iOS Simulator,name=iPhone 12,OS=latest"
      
      - name: Zip APP
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'app.zip'
          path: '/Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphonesimulator/*.app'

      - name: Deploy to AppCenter
        run: | 
          appcenter distribute release -f ./*.zip -g Collaborators --app SGT-Movilidad-COEX/Test_iOS_GitHubActions --build-version ${{ github.run_number }} --token ${{ secrets.APPCENTER_API_TOKEN }}
        # appcenter crashes upload-symbols -s /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug-iphonesimulator/*.app.dSYM --app SGT-Movilidad-COEX/Test_iOS_GitHubActions --token ${{ secrets.APPCENTER_API_TOKEN }}